CREATE DATABASE ExoProjetos
GO

USE ExoProjetos
GO

CREATE TABLE Projetos (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Titulo VARCHAR(150) NOT NULL,
    Inicio DATETIME NOT NULL DEFAULT GETDATE(),
    Status SMALLINT NOT NULL,
    Tecnologias VARCHAR(250)
)
GO

CREATE TABLE Usuarios (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nome VARCHAR(50) NOT NULL, 
    Email VARCHAR(50) NOT NULL UNIQUE,
    Senha VARCHAR(250) NOT NULL,
    Perfil SMALLINT NOT NULL
)
GO

ALTER TABLE Usuarios ALTER COLUMN Perfil INT NOT NULL
GO

ALTER TABLE Projetos ALTER COLUMN Status INT NOT NULL
GO